### ISSUE TITLE
Update EDG champion skin

### ISSUE THREAD

**Issue by xyzxyzfgdj** [R3nzTheCodeGOD/R3nzSkin#101]

**Comment by sonitaaaaa** [comment]
**1.** EDG is only for update **12.9** and is currently in beta. [**PBE Patch 12.9**](https://www.surrenderat20.net/2022/04/426-pbe-update-edg-high-noon-skins.html)


**2.** This tool only pulls assets from the instance you're using. For example, the current public version is **12.8**, and it is not possible to obtain the most recent resources, as was the case with the 12.9 beta.


**3.** This is Github, a website where you can discuss and share project issues. In addition, when writing the problem report, always include the full Title and Content. It's not nice, to simply register a spam name and file a bug report like this.


**4.** Because it is open source, you are free to clone and update it. If you don't know, then you should wait for a new version. And I've confirmed that this tool is still functional on 12.8.

**Comment by alphaaced** [comment]
> **1.** EDG is only for update **12.9** and is currently in beta. [**PBE Patch 12.9**](https://www.surrenderat20.net/2022/04/426-pbe-update-edg-high-noon-skins.html)
> 
> **2.** This tool only pulls assets from the instance you're using. For example, the current public version is **12.8**, and it is not possible to obtain the most recent resources, as was the case with the 12.9 beta. Because it doesn't exist yet.
> 
> and this tool does not support customSkin, so [this is what you need](https://github.com/customskinlol/cslol-manager) if you want to use it.
> 
> **3.** This is Github, a website where you can discuss and share project issues. In addition, when writing the problem report, always include the full Title and Content. It's not nice, to simply register a spam name and file a bug report like this.
> 
> **4.** Because it is open source, you are free to clone and update it. If you don't know, then you should wait for a new version. And I've confirmed that this tool is still functional on 12.8.
> 
> Edit: **Yes you can use this tool in PBE**

Do u have an idea how to fix some character abilities not taking effect into. LIKE annies R, anivia W, NUNU W. They all preset the defaults.

**Comment by alphaaced** [comment]
> > > **1.** EDG is only for update **12.9** and is currently in beta. [**PBE Patch 12.9**](https://www.surrenderat20.net/2022/04/426-pbe-update-edg-high-noon-skins.html)
> > > **2.** This tool only pulls assets from the instance you're using. For example, the current public version is **12.8**, and it is not possible to obtain the most recent resources, as was the case with the 12.9 beta. Because it doesn't exist yet.
> > > and this tool does not support customSkin, so [this is what you need](https://github.com/customskinlol/cslol-manager) if you want to use it.
> > > **3.** This is Github, a website where you can discuss and share project issues. In addition, when writing the problem report, always include the full Title and Content. It's not nice, to simply register a spam name and file a bug report like this.
> > > **4.** Because it is open source, you are free to clone and update it. If you don't know, then you should wait for a new version. And I've confirmed that this tool is still functional on 12.8.
> > > Edit: **Yes you can use this tool in PBE**
> > 
> > 
> > Do u have an idea how to fix some character abilities not taking effect into. LIKE annies R, anivia W, NUNU W. They all preset the defaults.
> 
> #1

so from what i understand, some skins will never be able to have these effects due to difference in skinchanger server and game server. Similar to effects of mythic skins?

**Comment by R3nzTheCodeGOD** [comment]
https://github.com/R3nzTheCodeGOD/R3nzSkin/issues/99#issuecomment-1113535518
