### ISSUE TITLE
Valorant's Vanguard anti-cheat will ban r3nzskin user after adding it?

### ISSUE THREAD

**Issue by nllkllta** [R3nzTheCodeGOD/R3nzSkin#1056]
Hello, 

i have a question since riot is adding Vanguard to League of Legends, does people that used the skinchanger will get banned? Because if yes, many accounts will get banned no?

**Comment by Dearmaevser** [comment]
I'm using R3 in Tencent's server, which is more strict in monitoring skin changes.

In the meantime I recently tried EZ's new skin with R3 and so far I'm still safe;

But recently I encountered a very serious problem that caused me to almost no longer use R3;I don't know if it's a problem with the Chinese server or R3 itself,The picture always teleports when I use it, just like the screen tearing caused by the refresh rate of the display out of sync,I'm pretty sure it's not the cause of computer performance and network latency.....

I'm just trying new skins with R3 right now

**Comment by KomariVGC** [comment]
Tencent's servers have always had this problem (screen tearing)

**Comment by KomariVGC** [comment]
Tencent's servers have always had this problem (screen tearing)

**Comment by Vanuty** [comment]
> I'm using R3 in Tencent's server, which is more strict in monitoring skin changes.
> 
> In the meantime I recently tried EZ's new skin with R3 and so far I'm still safe;
> 
> But recently I encountered a very serious problem that caused me to almost no longer use R3;I don't know if it's a problem with the Chinese server or R3 itself,The picture always teleports when I use it, just like the screen tearing caused by the refresh rate of the display out of sync,I'm pretty sure it's not the cause of computer performance and network latency.....
> 
> I'm just trying new skins with R3 right now
I think the picture problem you described may not be caused by r3, you can first check whether your graphics card configuration is very high, in that kind of situation lol frame rate will be very high, but your monitor does not support such a high frame rate then it will cause the picture of the tearing, in this case limit the frame rate of the game or turn on the graphic card's vertical synchronization on it!

**Comment by hotline1337** [comment]
It will just not inject.
