### ISSUE TITLE
STILL WORKING OR NO ?

### ISSUE THREAD

**Issue by Jenkiessss** [R3nzTheCodeGOD/R3nzSkin#1075]
ANYONEONE STILL USING R3NZSKIN ON THE RECENT VANGUARD UPDATE ????

**Comment by Kaynoc** [comment]
Vanguard is currently been testing in the Philippines server, the test will continue for 1 month more or less since I heard it's causing either performance issues or in generally in conflict with LoL old spaghetti codes. I'm still using R3Nz in EUW patch 14.5 (no vanguard yet) and it works flawlessly.

**Comment by Pierreluc15** [comment]
> Vanguard is currently been testing in the Philippines server, the test will continue for 1 month more or less since I heard it's causing either performance issues or in generally in conflict with LoL old spaghetti codes. I'm still using R3Nz in EUW patch 14.5 (no vanguard yet) and it works flawlessly.

Wrong Vanguard is in all server in april https://m.youtube.com/watch?v=t2niKNCmiUY&t=167s

**Comment by Pierreluc15** [comment]
> ANYONEONE STILL USING R3NZSKIN ON THE RECENT VANGUARD UPDATE ????

Vanguard is for now in test in Philippines
