### ISSUE TITLE
Functionality suggestion

### ISSUE THREAD

**Issue by Raevv** [R3nzTheCodeGOD/R3nzSkin#1079]
Hi, I have a question, since Samira Soulfighter has her own damage font, which is really pretty, would you, if it's possible to implement it, add a toggle to make us able to activate that font not matter the champ or skin we are currently using? Thanks for the work.

**Comment by Pierreluc15** [comment]
What you ask will not happen because in april 2024 R3nzSkin will no longer work for all server because of Vanguard https://m.youtube.com/watch?v=t2niKNCmiUY&t=167s and on announcement it clearly said this R3nzSkin will no longer be supported by 2024 due to Riot Games implementing [Valorant's Vanguard anti-cheat to League of Legends](https://support-leagueoflegends.riotgames.com/hc/en-us/articles/24169857932435-Riot-Vanguard-League-of-Legends-)
