### ISSUE TITLE
China Server New Critical error Info

### ISSUE THREAD

**Issue by Clownsw** [R3nzTheCodeGOD/R3nzSkin#23]
![Inked捕获_LI](https://user-images.githubusercontent.com/28394742/140636144-d08b2ba4-75e2-4c72-bb5d-3c3fe0410c8b.jpg)
**As shown in the figure, there is an error after CE injection on the left, and an error after forced injection on the right.**
**They have one thing in common, the KERNEL32 API address cannot be found**
**I think this is the most critical issue**
**Error Api: KERNEL32!InitOnceComplete**

**Comment by R3nzTheCodeGOD** [comment]
I think that's not the problem, if you get the message Injected successfully when you inject the DLL into the game with the cheat's own injector, the problem has nothing to do with it.

now i will teach you a method that requires no experience and knowledge. As we know, C++ codes work in a certain order, so you can find the error using MessageBox.

![image](https://user-images.githubusercontent.com/58574988/140653703-4a659b9f-643d-4971-8ce5-a64a77e54294.png)

If you don't get the message I found the client when you inject the cheat, now you know where the problem is :)
Now suppose the cheat has successfully hooked the game. So let's say we see the hook message.

![image](https://user-images.githubusercontent.com/58574988/140653944-365ee61e-c403-4cc5-9502-49d263a8ce47.png)

then the cheat will continue to work with the init_imgui() method, here the SkinDatabase::load() method will work, if there is no error it will exit there and switch to Hooks::init(). This way you can locate the error.

all you have to do is add a MessageBox to all the code blocks until you see the menu, if the game doesn't show you the message you typed into the MessageBox() then the problem is there.

**Comment by Clownsw** [comment]
> 我认为这不是问题，如果您在使用作弊者自己的注入器将DLL注入游戏时收到Injected successfully的消息，则问题与此无关。
> 
> 现在我将教你一个不需要经验和知识的方法。众所周知，C++ 代码按一定顺序运行，因此您可以使用 MessageBox 查找错误。
> 
> ![图片](https://user-images.githubusercontent.com/58574988/140653703-4a659b9f-643d-4971-8ce5-a64a77e54294.png)
> 
> 如果您在注入作弊时没有收到 I found the client 的消息，那么现在您知道问题出在哪里了 :) 现在假设作弊成功地吸引了游戏。所以假设我们看到了钩子消息。
> 
> ![图片](https://user-images.githubusercontent.com/58574988/140653944-365ee61e-c403-4cc5-9502-49d263a8ce47.png)
> 
> 然后作弊将继续使用 init_imgui() 方法，这里 SkinDatabase::load() 方法将起作用，如果没有错误它将退出那里并切换到 Hooks::init()。这样您就可以定位错误。
> 
> 您所要做的就是在所有代码块中添加一个 MessageBox，直到您看到菜单，如果游戏没有向您显示您在 MessageBox() 中键入的消息，那么问题就在那里。
![捕获](https://user-images.githubusercontent.com/28394742/140689480-5d2f4690-bfd7-416b-86ef-10109ea7166e.PNG)
游戏加载到:  Memory::Search(false);崩溃

**Comment by R3nzTheCodeGOD** [comment]
The problem is definitely in the signatures. Dump `League of Legends.exe` using the tutorial below and send it to me.

[Tutorial on how to dump the game](https://www.unknowncheats.me/forum/league-of-legends/320116-dump-lol-addresses-guide.html)

I will reverse the exe you sent when I am empty after posting

**Comment by R3nzTheCodeGOD** [comment]
I found the signatures except SwapChain, but I couldn't find SwapChain, I don't know why riot packed it.

![image](https://user-images.githubusercontent.com/58574988/140802729-4da935a9-417e-48bf-be9c-369064a74da1.png)

ManagerTemplate_AIHero_: `A1 ? ? ? ? 8B 54 24 14 53`
Riot_Renderer_MaterialRegistry_GetSingletonPtr: `E8 ? ? ? ? FF 75 38`

### If you replace the signatures in the cheat with the ones above and start the game in legacy DX9 mode, the cheat should work.

**Comment by Clownsw** [comment]
I changed the configuration to use DX9, but the above settings still don’t work @R3nzTheCodeGOD

**Comment by Clownsw** [comment]
I will re-upload a game dump later, so please take a look @R3nzTheCodeGOD

**Comment by R3nzTheCodeGOD** [comment]
Try this version I compiled by making the game DX9. If no other build is broken it should work.

[Download](https://cdn.discordapp.com/attachments/748413086083317811/907528568505004042/ChinaTest.rar)

if it still doesn't work keep debugging

**Comment by MyBin97** [comment]
It is now working properly, thanks for your help.

![Screen02](https://user-images.githubusercontent.com/70566876/140880960-78ac7d11-9169-4d34-a424-7e5077fe727d.png)

**Comment by Clownsw** [comment]
It is now working properly @R3nzTheCodeGOD

**Comment by Clownsw** [comment]
Thank you @R3nzTheCodeGOD @MyBin97

**Comment by Clownsw** [comment]
Excuse me, is there any difference between it and the code of the main branch? @R3nzTheCodeGOD

**Comment by R3nzTheCodeGOD** [comment]
[Source Code](https://cdn.discordapp.com/attachments/748413086083317811/907544372978016326/Src.rar)
