### ISSUE TITLE
Whether to support Chinese server LOL skin replacement？

### ISSUE THREAD

**Issue by ChinaNBSS** [R3nzTheCodeGOD/R3nzSkin#248]
The Chinese server has a detection mechanism for changing skins. I would like to ask if the software now supports changing skins for Chinese servers. @R3nzTheCodeGOD

**Comment by R3nzTheCodeGOD** [comment]
I am developing and updating this project for official riot servers like TR, EUW, NA.

If you want to use this project safely on servers like Korea, China, you should write your own injector and skip the detection vectors.

- **Supported Servers**
   - Official riot servers except Korea.
- **Unsupported Servers**
   - Korea and Garena servers. (Because these servers have extra security. I can't reverse engineer as I don't play on these servers.)

https://leagueoflegends.fandom.com/wiki/Servers

**Comment by hotline1337** [comment]
ChinaServer is supported.
