### ISSUE TITLE
Repair dead skin bug

### ISSUE THREAD

**Issue by tianya0529** [R3nzTheCodeGOD/R3nzSkin#335]
[13.5](https://github.com/tianya0529/R3nzSkin/releases/tag/v2.3.8) Update Repair dead skin bug.
For Chinese players, I provide a complete EXE,Recommended player use mode 2.
I'm sorry I didn't release it earlier. From yesterday to today, I had a full test day to release the new version I made.
I think I should solve this problem perfectly.

**Comment by tianya0529** [comment]
I'm sorry I didn't release it earlier. From yesterday to today, I had a full test day to release the new version I made。

**Comment by 68star89** [comment]
Can you release a chinese language version for chinese player in chinese mainland or taiwan?
虽然英文确实也看得懂，但有中文版还是舒服一点，而且汉化文本量应该也不太大…？
thanks very much

**Comment by tianya0529** [comment]
> Can you release a chinese language version for chinese player in chinese mainland or taiwan? 虽然英文确实也看得懂，但有中文版还是舒服一点，而且汉化文本量应该也不太大…？ thanks very much

 R3nzSkin13.5.1.zip  就是中文版本

**Comment by yanyanxinshi** [comment]
感谢你的工作

**Comment by XNeSizzzz** [comment]
> 

谢谢你

**Comment by rainzee** [comment]
I strongly discourage distributing your own closed-source compiled version of an open-source project; it's less about ethics and more about potential risk.

**Comment by rainzee** [comment]
See #337

**Comment by ZEERDEER** [comment]
有一点小bug，死后复活大概要2-5秒才会变成选定的皮肤，在这之前还是开局进去的皮肤。

**Comment by w004076** [comment]
Very thank you

**Comment by hotline1337** [comment]
Commit 9928813 fixes the problem.

**Comment by icode0698** [comment]
Why do you change an open source project to your own closed source project? I tried your compiled version, the system detected risks and the original author did not, because without your source code I can not detect whether false positives, can say what you are doing or what risks you are embedding. Please download carefully before you reply

为什么把一个开源项目转为你自己的闭源项目，我试了你编译的版本，系统检测存在风险而原作者的不会，由于没有你的源代码我无法甄别是否误报，可以说说你当中干什么或者说你在植入什么风险。在未回复之前请大家谨慎下载
