### ISSUE TITLE
Kha'Zix intensify R the body will be disordered

### ISSUE THREAD

**Issue by fulanGOD** [R3nzTheCodeGOD/R3nzSkin#339]
![QQ图片20230312054658](https://user-images.githubusercontent.com/127631597/224512840-7452effc-d7c1-47bd-b0ac-6cc240f6989c.png)

**Comment by fulanGOD** [comment]
@hotline1337 13.5

**Comment by tianya0529** [comment]
You can use R3nzSkin13.5.5  compiled by me
I solved the problem of Kha'Zix and Kai’sa,Please download R3nzSkin_ Injector13.5.zip  [Skin](https://github.com/tianya0529/R3nzSkin/releases/tag/v2.3.8)

**Comment by icode0698** [comment]
Why do you change an open source project to your own closed source project? I tried your compiled version, the system detected risks and the original author did not, because without your source code I can not detect whether false positives, can say what you are doing or what risks you are embedding. Please download carefully before you reply

为什么把一个开源项目转为你自己的闭源项目，我试了你编译的版本，系统检测存在风险而原作者的不会，由于没有你的源代码我无法甄别是否误报，可以说说你当中干什么或者说你在植入什么风险。在未回复之前请大家谨慎下载

**Comment by icode0698** [comment]
> 

Why do you change an open source project to your own closed source project? I tried your compiled version, the system detected risks and the original author did not, because without your source code I can not detect whether false positives, can say what you are doing or what risks you are embedding. Please download carefully before you reply

为什么把一个开源项目转为你自己的闭源项目，我试了你编译的版本，系统检测存在风险而原作者的不会，由于没有你的源代码我无法甄别是否误报，可以说说你当中干什么或者说你在植入什么风险。在未回复之前请大家谨慎下载

**Comment by icode0698** [comment]
> You can use R3nzSkin13.5.5 compiled by me I solved the problem of Kha'Zix and Kai’sa,Please download R3nzSkin_ Injector13.5.zip [Skin](https://github.com/tianya0529/R3nzSkin/releases/tag/v2.3.8)

Why do you change an open source project to your own closed source project? I tried your compiled version, the system detected risks and the original author did not, because without your source code I can not detect whether false positives, can say what you are doing or what risks you are embedding. Please download carefully before you reply

Why do you change an open source project to your own closed source project? I tried your compiled version, the system detected risks and the original author did not, because without your source code I can not detect whether false positives, can say what you are doing or what risks you are embedding. Please download carefully before you reply

**Comment by icode0698** [comment]
> You can use R3nzSkin13.5.5 compiled by me I solved the problem of Kha'Zix and Kai’sa,Please download R3nzSkin_ Injector13.5.zip [Skin](https://github.com/tianya0529/R3nzSkin/releases/tag/v2.3.8)

Why do you change an open source project to your own closed source project? I tried your compiled version, the system detected risks and the original author did not, because without your source code I can not detect whether false positives, can say what you are doing or what risks you are embedding. Please download carefully before you reply

为什么把一个开源项目转为你自己的闭源项目，我试了你编译的版本，系统检测存在风险而原作者的不会，由于没有你的源代码我无法甄别是否误报，可以说说你当中干什么或者说你在植入什么风险。在未回复之前请大家谨慎下载

**Comment by fulanGOD** [comment]
> 可以用我编的R3nzSkin13.5.5我解决了Kha'Zix和Kai'sa的问题，请下载R3nzSkin_ Injector13.5.zip[皮肤](https://github.com/tianya0529/R3nzSkin/releases/tag/v2.3.8)

I just tried,your version is the same as the author's version,have you tried it yourself?

**Comment by fulanGOD** [comment]
> You can use R3nzSkin13.5.5 compiled by me I solved the problem of Kha'Zix and Kai’sa,Please download R3nzSkin_ Injector13.5.zip [Skin](https://github.com/tianya0529/R3nzSkin/releases/tag/v2.3.8)

Kha'Zix intensify R the same problem will occur

**Comment by tianya0529** [comment]
> 

检测到风险只是因为封装的EXE是使用易语言进行编译，R3项目的编译的DLL并不会存在风险

**Comment by icode0698** [comment]
> > 
> 
> 检测到风险只是因为封装的EXE是使用易语言进行编译，R3项目的编译的DLL并不会存在风险

谢谢，我下载的是dll版本并非exe版本，dll版本检测有风险，建议你fork开源pj仍然采用开源编译

**Comment by tianya0529** [comment]
> > > 
> > 
> > 
> > 检测到风险只是因为封装的EXE是使用易语言进行编译，R3项目的编译的DLL并不会存在风险
> 
> 谢谢，我下载的是dll版本并非exe版本，dll版本检测有风险，建议你fork开源pj仍然采用开源编译

DLL我进行了VMP加壳 使内部特征混淆 如果需要我可以发布不加VMP的版本

**Comment by icode0698** [comment]
> > > > 
> > > 
> > > 
> > > 检测到风险只是因为封装的EXE是使用易语言进行编译，R3项目的编译的DLL并不会存在风险
> > 
> > 
> > 谢谢，我下载的是dll版本并非exe版本，dll版本检测有风险，建议你fork开源pj仍然采用开源编译
> 
> DLL我进行了VMP加壳 使内部特征混淆 如果需要我可以发布不加VMP的版本，因为我对一些英雄的问题进行了修复，我并不想开源使一些人拿去盈利，对于使用者来说，并不会造成一些影响，只是个人看不惯开源项目进行盈利，我对R3进行二次开发，修复一些存在的问题，我无偿发布我所编译的版本，并提供更为简便的使用方式

👍👍

**Comment by tianya0529** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 检测到风险只是因为封装的EXE是使用易语言进行编译，R3项目的编译的DLL并不会存在风险
> > > 
> > > 
> > > 谢谢，我下载的是dll版本并非exe版本，dll版本检测有风险，建议你fork开源pj仍然采用开源编译
> > 
> > 
> > DLL我进行了VMP加壳 使内部特征混淆 如果需要我可以发布不加VMP的版本，因为我对一些英雄的问题进行了修复，我并不想开源使一些人拿去盈利，对于使用者来说，并不会造成一些影响，只是个人看不惯开源项目进行盈利，我对R3进行二次开发，修复一些存在的问题，我无偿发布我所编译的版本，并提供更为简便的使用方式
> 
> 👍👍

我的github上最新的13.5.6 已经解决了社区内目前还存在的卡兹克 卡莎 天使的换肤问题，并且DLL未进行VMP加密编译，风险问题你可以再看下是否还存在，我在腾讯哈勃分析上也分析了我的压缩包，并没有存在所说的木马病毒，具体行为分析你也可以自己看下 [13.5.6](https://github.com/tianya0529/R3nzSkin/releases/tag/v2.3.8)

**Comment by hotline1337** [comment]
Deleted comment due to a malware spreading from user tianya0529.
