### ISSUE TITLE
Anxious injector

### ISSUE THREAD

**Issue by Djntif** [R3nzTheCodeGOD/R3nzSkin#34]
It's easy to get a ban on a Korean server. So I'm not sure if I can use it. Please help me.

If possible, can you make a safe injector? Excluding Load Library Injectors

**Comment by R3nzTheCodeGOD** [comment]
Sorry, but this is github platform where software is developed rather than asking for software. I do not offer a feature like you will not be banned in my cheat, this is not an issue that interests me. If you do not want to be banned, you will either code your own cheat or pay money and get service from cheat sites.

`Note:` This cheat is definitely not suitable for direct use on the Korean server. On the Korean server, if you want to use a skin changer, it would be better to write an external cheat.

**also don't open new thread on repo to reply**
