### ISSUE TITLE
Ban rate?

### ISSUE THREAD

**Issue by SatanicScripter** [R3nzTheCodeGOD/R3nzSkin#39]
The title explain all (a friend told me this question... i use in my first acc since 3 month ago and i never get banned THANKS R3zn)

**Comment by W0ksler** [comment]
Riot already stated they dont ban Skin Changers. They dont bother with it since it doesnt give the player any advantages.

They ban custom skins though. Skin Mods that messes with League's files are likely to get you banned, but a simple Skin Changer isn't.

Been using Skin Changers since 2018 and never had a ban.

https://support-leagueoflegends.riotgames.com/hc/en-us/articles/225266848-Third-Party-Applications

**Comment by SatanicScripter** [comment]
Thanks for solving my issue. I'll send it to my friend
