### ISSUE TITLE
New Skin Changer

### ISSUE THREAD

**Issue by Souplax1** [R3nzTheCodeGOD/R3nzSkin#402]
Dont download new skin version its trojan virus. Wait till they fix it.

**Comment by Viqnish** [comment]
Proof please.

**Comment by Nimzuie** [comment]
Admitedly if you put it in any virus analysis bench you can see it making internet requests to QQ a chinese media app which it should have no reason to do whatsoever with it just being a skin changer, basically it acts suspiciously just wait for an open source one. Also just because it works doesn't mean its safe.

**Comment by Souplax1** [comment]
> Proof please.

Most of biggest cheating site I wont say names, decline chinese "R3nzSkin" skin changer,because they can't upload in release mode. (skin.exe / Xprocess)

**Comment by Viqnish** [comment]
Hmm. Thanks for discrediting yourself so I dont have to be concerned. Regards

**Comment by Nimzuie** [comment]
?? Nice "nu uh" argument. Anyway don't download suspicious files or do not my issue
