### ISSUE TITLE
New Temporary Skinchanger.

### ISSUE THREAD

**Issue by OkashiWantavi** [R3nzTheCodeGOD/R3nzSkin#409]
-redacted-

**Comment by Deaiman** [comment]
dont download that. its fucking trojan

**Comment by OkashiWantavi** [comment]
> dont download that. its fucking trojan

DId you even try it? stop calling me out for shit randomly

Thank you.

**Comment by Deaiman** [comment]
yes i tried it on vm. Still it works but with ton of trojans.

**Comment by Azagarialol** [comment]
In our discord server, we will tell every update on the skin changers, malwares and updates with league. We have a great support team and we will always help you with the skin changer. We have 1 in our Links channel.

https://discord.gg/QhSsahfR

If you can't verify send me a DM.

**Comment by GolloChad** [comment]
When I try to open it, nothing opens and I already deactivated the antivirus

**Comment by veenx** [comment]
Nice trojan btw

**Comment by meidoyakui** [comment]
I'm surprised I have to tell you guys this, but stop downloading suspicious files.
The reason this project was trustworthy was because it was a free open source project rather than a closed source suspicious injector.
How do you know if you can trust something?
It's open source, or it is a cheat you willingly PAY monthly for.
Do you seriously think people are kind enough to develop advanced tools and injectors for free and share them without some type of payment somehow? The payment here is in the form of a trojan instead of a monthly fee.
If something is too good to be true, it's usually because it is.

**Comment by hkthomas** [comment]
> 我很惊讶我必须告诉你们这个，但停止下载可疑文件。这个项目值得信赖的原因是因为它是一个免费的开源项目，而不是一个闭源可疑注入器。你怎么知道你是否可以信任某事？它是开源的，或者它是你愿意每月支付的作弊。您是否真的认为人们愿意免费开发高级工具和注射器，并在没有某种付款的情况下共享它们？这里的付款以特洛伊木马的形式而不是月费。如果某件事好得令人难以置信，那通常是因为它确实如此。

网络行情，要么付费，要么付出代价，显然。

**Comment by sugiharaxo** [comment]
> https://www.virustotal.com/gui/file/07e46b21afc4ab1bef8fc293db0daf6a5440c59584617b52c1c348d6e83655b3
> 
> Brother...

Yes, software that has anything to do with injection will get flagged as malicious because of its nature. Have you tried putting in the original R3nzSkin file into virustotal? It flags 30/68

**Comment by alphaaced** [comment]
Whatever you do, never trust a tool called Bingo. It's a banking trojan with many proofs from virustotal to actual experts decrypting it.

**Comment by hotline1337** [comment]
Do not promote or share any binaries in this repository.
