### ISSUE TITLE
Trojan:Win32/Mamson.A!ml

### ISSUE THREAD

**Issue by chlckenmcnuggets** [R3nzTheCodeGOD/R3nzSkin#497]
Trojan:Win32/Mamson.A!ml
what the fuck is this shit. it pops up in my windows security when trying to unzip the file and is seemingly in the injector since the dll unzips just fine. not using it until this gets resolved somehow

**Comment by chlckenmcnuggets** [comment]
okay i just found the closed issues tab. its probably the same thing yeah ?

**Comment by EzequielDM** [comment]
This is open source, read the code. You can simply not open it, it's fine.

**Comment by chlckenmcnuggets** [comment]
yes fair enough i guess but i have no clue about code and i just want my silly little skins to work in my sily little game :(

**Comment by amyrillis** [comment]
it is just a false positive. im using this skin changer for almost a month and nothing happened. just allow it through your antivirus and it will run smoothly.
now its your choice

**Comment by hotline1337** [comment]
That is a false positive. The skin changer as well as the injector uses some Win32 API's that aren't commonly used in normal programs. The project is open-source, so you are welcome to compile the skin changer on your own, otherwise disable your antivirus and add the folder with the binaries to the exclusion list.
