### ISSUE TITLE
Trojan detected from windows security

### ISSUE THREAD

**Issue by taleskeri** [R3nzTheCodeGOD/R3nzSkin#521]
Hi, I want to ask anyone that has a lot of experience with this program does it have viruses or ?
Also, anyone that is using it for a long time, is it bannable on your league of legends account? 
Thanks!

**Comment by Michaalv** [comment]
false

**Comment by taleskeri** [comment]
false what bro i dont understand

**Comment by yurikoshi** [comment]
be careful... 

https://www.virustotal.com/gui/file/c6c5052f927c8928fa3d1d477aa10b0475464757e55050ab8e4efe65904331c5/detection

**Comment by hotline1337** [comment]
That is a false positive. The skin changer as well as the injector uses some Win32 API's that aren't commonly used in normal programs. The project is open-source, so you are welcome to compile the skin changer on your own, otherwise disable your antivirus and add the folder with the binaries to the exclusion list.

I'm tired of closing issues like this one is like a 10 issue relating to this issue this week. Please check closed issues before posting an another one.
