### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by Timmcanpyy** [R3nzTheCodeGOD/R3nzSkin#526]
Ye so my pc is detecting a virus from the files.Is it normal?

**Comment by taleskeri** [comment]
yeah just add an exclusion and add the folder where your injector is extracted, its a false positive virus.

**Comment by hotline1337** [comment]
That is a false positive. The skin changer as well as the injector uses some Win32 API's that aren't commonly used in normal programs. The project is open-source, so you are welcome to compile the skin changer on your own, otherwise disable your antivirus and add the folder with the binaries to the exclusion list.

I'm tired of closing issues like this one is like a 10 issue relating to this issue this week. Please check closed issues before posting an another one.
