### ISSUE TITLE
trojan

### ISSUE THREAD

**Issue by el7ag10y** [R3nzTheCodeGOD/R3nzSkin#531]
when i download my antivirus says Trojan:Win32/Conteban.A!ml

**Comment by yamatodoppelganger** [comment]
same bro

**Comment by yamatodoppelganger** [comment]
I read the info about the virus on a couple of sites they write supposedly a miner

**Comment by hotline1337** [comment]
That is a false positive. The skin changer as well as the injector uses some Win32 API's that aren't commonly used in normal programs. The project is open-source, so you are welcome to compile the skin changer on your own, otherwise disable your antivirus and add the folder with the binaries to the exclusion list.

I'm tired of closing issues like this one is like a 10 issue relating to this issue this week. Please check closed issues before posting an another one.
