### ISSUE TITLE
windows security 

### ISSUE THREAD

**Issue by Dargonell27** [R3nzTheCodeGOD/R3nzSkin#546]
my device keeps labelling the app as a virus causing it to crash a lot.
even when i say ""allow on device" it still keeps happening. 
is there a way to make this stop.

**Comment by hotline1337** [comment]
That is a false positive. The skin changer as well as the injector uses some Win32 API's that aren't commonly used in normal programs. The project is open-source, so you are welcome to compile the skin changer on your own, otherwise disable your antivirus and add the folder with the binaries to the exclusion list.

I'm tired of closing issues like this one is like a 10 issue relating to this issue this week. Please check closed issues before posting an another one.

The program needs Administrator privileges to perform certain actions to ensure that the skin changer works correctly.
