### ISSUE TITLE
Explanation for why the injector is marked as a trojan?

### ISSUE THREAD

**Issue by aiicarus** [R3nzTheCodeGOD/R3nzSkin#555]
I'm willing to trust this isn't a virus and that the most I'm risking is a league account but I want to understand why it's marked as one. I understand they use old windows API's but why would that mark it explicitly as a trojan? I'm not skilled enough to scour through the source code and find a miner or keylogger or whatever but what actually causes the false positive?

**Comment by rainzee** [comment]
Any EXE without a Microsoft signature will be mark.

**Comment by hotline1337** [comment]
That is a false positive. The skin changer as well as the injector uses some Win32 API's that aren't commonly used in normal programs. The project is open-source, so you are welcome to compile the skin changer on your own, otherwise disable your antivirus and add the folder with the binaries to the exclusion list.

I'm tired of closing issues like this one is like a 10 issue relating to this issue this week. Please check closed issues before posting an another one.

**Comment by jacaaha11** [comment]
I have a problem with r3nzskins, a Trojan is displayed, but I'm wondering why, even after accepting this Trojan, the computer deletes this program every few hours because a new Trojan is still displayed?
