### ISSUE TITLE
its a virus

### ISSUE THREAD

**Issue by MrTsud0** [R3nzTheCodeGOD/R3nzSkin#570]
its a trojan virus lmao

**Comment by VenraUwU** [comment]
spamming doesnt make you more believable just give us any sort of evidence

**Comment by hotline1337** [comment]
That is a false positive. The skin changer as well as the injector uses some Win32 API's that aren't commonly used in normal programs. The project is open-source, so you are welcome to compile the skin changer on your own, otherwise disable your antivirus and add the folder with the binaries to the exclusion list.

I'm tired of closing issues like this one is like a 10 issue relating to this issue this week. Please check closed issues before posting an another one.

**Comment by ppmeph** [comment]
https://www.reddit.com/r/LoLcustom/comments/13qrg5a/the_virus_of_r3nzskin_is_not_false_positive_its/ 
this is shit
