### ISSUE TITLE
its fuckkking virus okay? dont trust this guy

### ISSUE THREAD

**Issue by MrTsud0** [R3nzTheCodeGOD/R3nzSkin#571]
it has trojan horse, if you dont know trojan horse means just search it on google or something

**Comment by VenraUwU** [comment]
Can you give literally ANY evidence except for saying "oh is virus!!" ? we/i know  what a trojan is and computers detect these kind of software as virus bcs they do what viruses do just not harmful for your PC (in theory) but can you tell us why THIS is a trojan?

**Comment by hotline1337** [comment]
That is a false positive. The skin changer as well as the injector uses some Win32 API's that aren't commonly used in normal programs. The project is open-source, so you are welcome to compile the skin changer on your own, otherwise disable your antivirus and add the folder with the binaries to the exclusion list.

I'm tired of closing issues like this one is like a 10 issue relating to this issue this week. Please check closed issues before posting an another one.
