### ISSUE TITLE
trojan file 

### ISSUE THREAD

**Issue by Alessail** [R3nzTheCodeGOD/R3nzSkin#584]
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/138065973/da3b98ce-404f-42ef-98bc-39d25c799cfe)

**Comment by hotline1337** [comment]
That is a false positive. The skin changer as well as the injector uses some Win32 API's that aren't commonly used in normal programs. The project is open-source, so you are welcome to compile the skin changer on your own, otherwise disable your antivirus and add the folder with the binaries to the exclusion list.

I'm tired of closing issues like this one is like a 10 issue relating to this issue this week. Please check closed issues before posting an another one.
