### ISSUE TITLE
R3nz is a virus

### ISSUE THREAD

**Issue by darklvstl** [R3nzTheCodeGOD/R3nzSkin#589]
I tried downloading it and it popped up that there's  trojan in it. I ignored it and deleted the file in my trashbin until 1 day later my Darksiders III was randomly deleted, as well as some sai files. I went to the trash bin(where the r3nz was) and got a popup **_.https://cdn.discordapp.com/attachments/969140741219713074/1121120187190624366/image.png_**
 I had to factory reset my Pc.
Today I tried downloading it ONCE again after and got this _**https://cdn.discordapp.com/attachments/968968726554742784/1124013363010228324/image.png**_
Honestly I cannot bother with this program. If it's too good to be true there's always a catch.

**Comment by pmetemp** [comment]
You have a program injecting a DLL into another program ofc it's going to show as virus. It's called a false positive. The project is literally open source you can read it yourself.

**Comment by piee-kun** [comment]
you do realise Wacapew.C!ml is a placeholder for heuristic detections right? all that means is that Windows Defender is guessing that this file is a virus based on its behaviour. some viruses usually hook themselves into other programs to hide their execution so it doesn't show up on the process list, requiring a more in-depth scanning technique from the end user. guess what R3nzSkin does to your League client. it injects a DLL. your files disappearing is entirely a coincidence, you can search up in the source code yourself to check if anything is being deleted, which i doubt.

**Comment by hotline1337** [comment]
That is a false positive. The skin changer as well as the injector uses some Win32 API's that aren't commonly used in normal programs. The project is open-source, so you are welcome to compile the skin changer on your own, otherwise disable your antivirus and add the folder with the binaries to the exclusion list.

I'm tired of closing issues like this one is like a 10 issue relating to this issue this week. Please check closed issues before posting an another one.
