### ISSUE TITLE
Is this a trojan?

### ISSUE THREAD

**Issue by EJKGorun** [R3nzTheCodeGOD/R3nzSkin#590]

**Comment by promptDeveloper** [comment]
I'm not even able to bring the menu up, it says to press insert im on a mac so im pressing fn + enter but I can't the menu to come up.

**Comment by hotline1337** [comment]
> I'm not even able to bring the menu up, it says to press insert im on a mac so im pressing fn + enter but I can't the menu to come up.

R3nzSkin is not supported on macOS.

**Comment by hotline1337** [comment]
That is a false positive. The skin changer as well as the injector uses some Win32 API's that aren't commonly used in normal programs. The project is open-source, so you are welcome to compile the skin changer on your own, otherwise disable your antivirus and add the folder with the binaries to the exclusion list.

I'm tired of closing issues like this one is like a 10 issue relating to this issue this week. Please check closed issues before posting an another one.

**Comment by EJKGorun** [comment]
> That is a false positive. The skin changer as well as the injector uses some Win32 API's that aren't commonly used in normal programs. The project is open-source, so you are welcome to compile the skin changer on your own, otherwise disable your antivirus and add the folder with the binaries to the exclusion list.
> 
> I'm tired of closing issues like this one is like a 10 issue relating to this issue this week. Please check closed issues before posting an another one.

sry bro just wanted to know if it was safe, im not really good at this stuff
