### ISSUE TITLE
UPDATER

### ISSUE THREAD

**Issue by failure1975** [R3nzTheCodeGOD/R3nzSkin#598]
when is the update coming out? im getting errors when being launched in game. cant use the temporary file cuz the skin resets everytime i died and crashes my game when the match is finished.

**Comment by HadockKali** [comment]
Could you share more information about your problems? I can try to help.
If you have persistent issues you can contact me on Discord: hadock

**Comment by failure1975** [comment]
i already found the updated one. but the problem is my computer detects that it has trojan.

**Comment by HadockKali** [comment]
It's normal behavior because the executable isn't signed by a Microsoft-approved vendor, and anything related to memory manipulation, injection or otherwise circumventing a certain way of how things should work normally it's triggering any AV as a false-positive, as you can see the code is open source and you can look through it yourself, there it's nothing malicious. Depending if you downloaded a modified/already-compiled version of it that might be the problem, always compile it yourself or download the binary file from the **Release** section of the repo.  Try to compile the project yourself, you don't need any experience/additional knowledge just follow the guide in the README.md file. I hope that solved your issue, if not please don't hesitate to reply. Have a good day!
