### ISSUE TITLE
easy lauch

### ISSUE THREAD

**Issue by Lestueurs** [R3nzTheCodeGOD/R3nzSkin#608]
hello sir R3nzTheCodeGOD, I am writing to you because I do not understand what I have to do to use the mod. I don't know if it's possible for you to create an .exe version and easier to use how it's mods : https://killerskins.com or https://leagueskin.net/p/download-mod-skin-2020-chn

**Comment by HadockKali** [comment]
> hello sir R3nzTheCodeGOD, I am writing to you because I do not understand what I have to do to use the mod. I don't know if it's possible for you to create an .exe version and easier to use how it's mods : https://killerskins.com or https://leagueskin.net/p/download-mod-skin-2020-chn

This tool only let's you equip already existing skins in the game that you don't own. It's not a Custom Skin tool it's simply a skin changer for the skins that already exist within the game.

**Comment by Lestueurs** [comment]
my antivirus deletes the .exe file in it that's why it didn't work

**Comment by hotline1337** [comment]
> my antivirus deletes the .exe file in it that's why it didn't work

That is a false positive. The skin changer as well as the injector uses some Win32 API's that aren't commonly used in normal programs. The project is open-source, so you are welcome to compile the skin changer on your own, otherwise disable your antivirus and add the folder with the binaries to the exclusion list.

I'm tired of closing issues like this one is like a 10 issue relating to this issue this week. Please check closed issues before posting an another one.
