### ISSUE TITLE
Virused on w11

### ISSUE THREAD

**Issue by miksiak420** [R3nzTheCodeGOD/R3nzSkin#617]
Can someone help me? I got virused while i was turning off my antivirus to launch skinchanger, i didnt have any viruses before. ill be thankful for help.

**Comment by hotline1337** [comment]
That is a false positive. The skin changer as well as the injector uses some Win32 API's that aren't commonly used in normal programs. The project is open-source, so you are welcome to compile the skin changer on your own, otherwise disable your antivirus and add the folder with the binaries to the exclusion list.

I'm tired of closing issues like this one is like a 10 issue relating to this issue this week. Please check closed issues before posting an another one.
