### ISSUE TITLE
There is no exe in R3nzSkin_Injector and R3nzSkin folder

### ISSUE THREAD

**Issue by mariostart01** [R3nzTheCodeGOD/R3nzSkin#636]
![r1](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/75117256/56d7fd89-ea75-4aeb-a5fa-5eed46473684)
![s2](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/75117256/b6dd69de-6510-4573-ac0d-85e4803d06b7)

**Comment by mariostart01** [comment]
> ...That's the code... not the compiled release...

So how do i use it?

**Comment by Bl1nterS** [comment]
Go to the original page and instead of clicking on the big green "code" button and pressing "download zip" scroll down a bit and look at the part on your right
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/140167594/5ee8cd05-217b-4d50-a0c1-b26db19a3e9c)
Click on it and and select R3nzSkin.zip
Now extract it and you can run the injector
