### ISSUE TITLE
idk what dis is 

### ISSUE THREAD

**Issue by synzxd** [R3nzTheCodeGOD/R3nzSkin#653]
i got on my antivirus a RiskWare.DDl injector and it tells me to delete it but ig its safe? someone help plz i have 0 idea

also is there any way to make the program not open every time a game starts so it just kinda works on the backround

**Comment by hotline1337** [comment]
That is a false positive. The skin changer as well as the injector uses some Win32 API's that aren't commonly used in normal programs. The project is open-source, so you are welcome to compile the skin changer on your own, otherwise disable your antivirus and add the folder with the binaries to the exclusion list.

I'm tired of closing issues like this one is like a 10 issue relating to this issue this week. Please check closed issues before posting an another one.
