### ISSUE TITLE
First time using this SkinChanger, should i be worry about this message?

### ISSUE THREAD

**Issue by mariomo16** [R3nzTheCodeGOD/R3nzSkin#657]
Probably this is normal, but it's my first time using this SkinChanger and i want to be 100% sure.
I get this message: Trojan:Script/Phonzy.B!ml

Should i be worry?

**Comment by hotline1337** [comment]
That is a false positive. The skin changer as well as the injector uses some Win32 API's that aren't commonly used in normal programs. The project is open-source, so you are welcome to compile the skin changer on your own, otherwise disable your antivirus and add the folder with the binaries to the exclusion list.

I'm tired of closing issues like this one is like a 10 issue relating to this issue this week. Please check closed issues before posting an another one.
