### ISSUE TITLE
there is trojan 

### ISSUE THREAD

**Issue by kioraaa** [R3nzTheCodeGOD/R3nzSkin#660]
XD

**Comment by hotline1337** [comment]
That is a false positive. The skin changer as well as the injector uses some Win32 API's that aren't commonly used in normal programs. The project is open-source, so you are welcome to compile the skin changer on your own, otherwise disable your antivirus and add the folder with the binaries to the exclusion list.

I'm tired of closing issues like this one is like a 10 issue relating to this issue this week. Please check closed issues before posting an another one.

**Comment by 14fedora** [comment]
> That is a false positive. The skin changer as well as the injector uses some Win32 API's that aren't commonly used in normal programs. The project is open-source, so you are welcome to compile the skin changer on your own, otherwise disable your antivirus and add the folder with the binaries to the exclusion list.
> 
> I'm tired of closing issues like this one is like a 10 issue relating to this issue this week. Please check closed issues before posting an another one.

hi i just wanna say this. i tried downloading  skin changer  last week but the windows defender did not keep the files and tried to disable defender but it still deletes it bc it detectes it i tried many solution and totorials to disable windows defender and bc it deletes the files i was downloading it again and again. but one time when i redownload the defender did not delete the files but it still detecte torjan,i tried deleting it from defender but it cant delete ,after that my pc strated slowing down .so i had to do a full clean up to my pc ,do u have a reason for this?
