### ISSUE TITLE
injection failed

### ISSUE THREAD

**Issue by tianyu0919** [R3nzTheCodeGOD/R3nzSkin#747]
![image](https://github.com/R3nzTheCodeGOD/R3nzSkin/assets/50062848/faf15cbf-4cd1-44d2-b0e2-cc9e79468b29)

why？

**Comment by BakaFT** [comment]
The injector is trying to establish a connection to github api service but you are in china mainland.
btw you should inject it by dll proxing instead of using injector cuz the Anti-Cheat expert is working on tencent build.

reference: https://github.com/R3nzTheCodeGOD/R3nzSkin/blob/main/R3nzSkin_Injector/Injector.cpp#L145


说人话，你别用注入器，这玩意国服又用不了。直接dll改名放到游戏目录下，具体做法百度贴吧我记得有。

**Comment by BakaFT** [comment]
#544 但凡你多翻几个Issue

**Comment by tianyu0919** [comment]
> #544 但凡你多翻几个Issue

我没玩国服(马服)。。。我玩的台服。使用拳头登录器登录游戏。而不是马服

**Comment by tianyu0919** [comment]
> #544 但凡你多翻几个Issue

之前可以直接使用，现在不知道为啥我这不行。我朋友他们可以使用，所以我提了一个issue，那如果玩台服也是根据你发的那个改名dll文件吗？

**Comment by tianyu0919** [comment]
> 
我试过了，一直弹框，关掉还是弹，而且是乱码。

**Comment by tianyu0919** [comment]
> The injector is trying to establish a connection to github api service but you are in china mainland. btw you should inject it by dll proxing instead of using injector cuz the Anti-Cheat expert is working on tencent build.
> 
> reference: https://github.com/R3nzTheCodeGOD/R3nzSkin/blob/main/R3nzSkin_Injector/Injector.cpp#L145
> 
> 说人话，你别用注入器，这玩意国服又用不了。直接dll改名放到游戏目录下，具体做法百度贴吧我记得有。

我试过了，一直弹窗，而且是乱码，一直弹。关掉还会弹。

**Comment by hotline1337** [comment]
use a proxy, like Cloudflare WARP
